# This is a basic workflow to help you get started with Actions

name: milestone to project issues
on:
  issues:
    types: [milestoned]

jobs:
  github-actions-automate-projects:
    runs-on: ubuntu-latest
    steps:
    - name: add-new-issues-to-repository-based-project-column
      uses: docker://takanabe/github-actions-automate-projects:v0.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_PROJECT_URL: https://github.com/users/stilnat/projects/6
        GITHUB_PROJECT_COLUMN_NAME: Todo
