# This is a basic workflow to help you get started with Actions

name: milestone to project issues
on:
  issues:
    types: [milestoned]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
    - name: Assign issues and pull requests with `bug` label to project 3
      uses: srggrs/assign-one-project-github-action@1.2.1
      with:
        project: 'https://github.com/users/stilnat/projects/6'
        column_name: 'To Do'
